site_name: k7a-tomohiro
site_url: https://k7a-tomohiro.github.io/
site_description: k7a-tomohiro's personal website.
site_author: k7a-tomohiro
copyright: Copyright &copy; 2025 k7a-tomohiro.
repo_name: k7a-tomohiro
repo_url: https://github.com/k7a-tomohiro
edit_uri: edit/main/website/

docs_dir: "./website"
strict: false

extra_css:
  - _customize/mkdocs.css
  - _customize/asciinema-player.css
extra_javascript:
  - _customize/mathjax.js
  - _customize/mermaid.js
  - _customize/asciinema-player.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

exclude_docs: |
  README.md
  .gitignore
  .gitkeep
  *.drawio

theme:
  name: material
  locale: en
  highlightjs: true
  logo: _customize/icon.png
  favicon: _customize/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
    - navigation.path
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.follow

plugins:
  - search
  - tags
  - blog
  - mkdocs-issues-plugin:
      log_level: "INFO"
      configs:
        - service: 'github'
          base_url: 'https://github.com'
          api_url: 'https://api.github.com'
          token: $GITHUB_TOKEN

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - smarty
  - admonition
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path: "./website"
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: true
  analytics:
    provider: google
    property: G-XDXFERZ4Z0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k7a-tomohiro

nav:
  - Projects:
      - projects/index.md
  - Blog:
      - blog/index.md
  - MyLearn:
      - Container:
        - learn/container/index.md
      - Kubernetes:
        - learn/kubernetes/index.md
      - Ansible:
        - learn/ansible/index.md
      - Terraform:
        - learn/terraform/index.md
      - Go:
        - learn/go/index.md
      - Rust:
        - learn/rust/index.md
  #########*#########*#########*#########*#########
  # DO NOT ADD LINES BELOW.
  # AUTO GENERATED NAV COMES BELOW.
